### ISSUE TITLE
NetkillUi

### ISSUE THREAD

**Issue by iphizzle** [extigy/extigy.github.io#1]
Can you please please update this tweak to work with CoolStars stashing tweak?! I can't uninstall stashing because it would put me at over 100% capacity, but I really want to have this tweak. Thank you!!!

**Comment by extigy** [comment]
I'm sorry, but I am no longer actively working on this tweak. I may get around to it eventually but all of my current "tweak dev time" is concentrated on Waveflow.

I am told that you can reinstall stashing after opening netkillui it at least once and it works. So a solution (although an annoying one) might be to remove stashing and some other tweaks to bring you under 100% use, then install netkillui, open it once, then reinstall stashing, then reinstall your other tweaks.
